### ISSUE TITLE
change tab size to 4

### ISSUE THREAD

**Issue by Innov8graphics** [SeanJM/css-clean#10]
Hi, can't change tab size to 4

Could you help please?
Thanks...

**Comment by SeanJM** [comment]
Issue is fixed. Tab size will be detected automatically now.

**Comment by Innov8graphics** [comment]
@SeanJM Thank you!
The package is brilliant, is there a way to add a config file?
There are a few items I would like to change... remove line breaks on comments, and a few other alignment tweaks on css rules.
