### ISSUE TITLE
CSS-Clean the Last Character from CSS Class/Selector etc

### ISSUE THREAD

**Issue by bnchndlr** [SeanJM/css-clean#12]
Hey mate, there seems to be a problem running your tool where it cuts off the end character of the final css selectors.

I have made a gif below that illustrates the error.

![css-clean](https://cloud.githubusercontent.com/assets/1875146/14010358/87a032ca-f1e8-11e5-8695-0753799e4ec2.gif)

**Comment by SeanJM** [comment]
Hey nice gif and thank you for taking the time, posting the CSS code for bugs is the most useful you can display what broke it.

**Comment by SeanJM** [comment]
It's the position of the '{' brace. Good catch.

**Comment by bnchndlr** [comment]
No worries mate :) Glad I could help! Awesome little plugin.




On Mar 24, 2016, at 11:13 PM, Sean MacIsaac <notifications@github.com> wrote:

It's the position of the '{' brace. Good catch.

**Comment by SeanJM** [comment]
Fixed
