### ISSUE TITLE
Empty selectors without line break

### ISSUE THREAD

**Issue by HannesDev** [SeanJM/css-clean#14]
Personally I think it's cleaner if a empty selector is in one line.

Example:
```css
thead {}

tbody {}

tfoot {}
```

instead of
```css
thead {
}

tbody {
}

tfoot {
}
```

---
Anyway, css-clean is great plugin! Great work so far, Sean! Keep it up! :)

**Comment by SeanJM** [comment]
Thanks @HannesDev ;-)
