### ISSUE TITLE
Sorting variables

### ISSUE THREAD

**Issue by HannesDev** [SeanJM/css-clean#15]
I don't think it is useful to sort variables alphabetically because it can bring up some serious problems.
Sass is read from top to bottom, so if variables are ordered in a new way it can cause errors like *Undefined variable*.

Example:
````
$gutter: 1.618;

$gu02: $gutter*0.2em;
$gu05: $gutter*0.5em;
$gu1:  $gutter*1em;
$gu2:  $gutter*2em;
$gu3:  $gutter*3em;
$gu4:  $gutter*4em;
````

should not be:
````
$gu1            : $gutter*1em;
$gu02           : $gutter*0.2em;
$gu2            : $gutter*2em;
$gu3            : $gutter*3em;
$gu4            : $gutter*4em;
$gu05           : $gutter*0.5em;
$gutter         : 1.618;
```

**Comment by SeanJM** [comment]
I'll leave this open, and if someone else agrees I'll remove it.

**Comment by SeanJM** [comment]
Variable sorting is gone.
