### ISSUE TITLE
Change default tab space?

### ISSUE THREAD

**Issue by omega-inspiron** [SeanJM/css-clean#18]
How would I be able to configure the tab space for alignment.  I'd like to change it from 2 to 4.  Is this possible?  BTW Thanks for this package.

**Comment by SeanJM** [comment]
Tabs are automatically detected. If you want 4 spaces, all you've got to do is have 4 spaces as your first like of indentation! :)

**Comment by omega-inspiron** [comment]
Thanks.

**Comment by SeanJM** [comment]
You're welcome!
