### ISSUE TITLE
Deletes valid CSS code. 

### ISSUE THREAD

**Issue by tinamayswinkels** [SeanJM/css-clean#19]
I installed this package, and on save my code does look beautiful, but it also seemed to delete lots of perfectly valid code leaving empty css selectors.

**Comment by SeanJM** [comment]
Hi @tinamayswinkels, your post is incomplete. If I could see the offending CSS code, I could fix the issue. This project is done in my free time so bare with me.

**Comment by SeanJM** [comment]
I also thank you for using it.

**Comment by SeanJM** [comment]
@tinamayswinkels I am closing the issue because I don't have enough information to fix your problem.
