### ISSUE TITLE
Experimental CSS properties

### ISSUE THREAD

**Issue by robert-m** [SeanJM/css-clean#2]
Any chance you can add support to ignore certain properties (or even add support) to experimental CSS properties such as the '**clip-path**'.

Also, I absolutely love this package! Best CSS beautifier I've come across. Amazing job @SeanJM

**Comment by SeanJM** [comment]
Yes

Sean

**Comment by SeanJM** [comment]
Added

**Comment by robert-m** [comment]
Hi @SeanJM - Thanks for the update but unfortunately its still removing a lot of valid css properties for me. I'm currently using the latest atom-css-clean 2.20.3 package. 

**MY CSS CODE**
#bt-slider {
	background-color: #2196f3;
	-webkit-clip-path: polygon(0 0, 100% 0, 100% 100%, 0 90%);
}
.hero-wrapper {
	-webkit-clip-path: polygon(0 0, 100% 0, 100% 84%, 0 100%);
	clip-path: polygon(0 0, 100% 0, 100% 90%, 0 100%);
	min-height: 95%;
}
**OUTPUT**
#bt-slider {
  background-color : #2196f3;
}

.hero-wrapper {}

**Comment by SeanJM** [comment]
I forgot to add '-prefix-' in the properties list. If you want to add missing properties, you can submit a pull request. You can find them in 'constants/PROPERTIES_LIST.js'
