### ISSUE TITLE
css-clean removing some rules

### ISSUE THREAD

**Issue by deepak-jacob** [SeanJM/css-clean#23]
Rules after direct child selector (>) is missing after clean,

li.somesel {
				display: block;
				> a {
					display: block;
					float: left;
				}
}

After clean,

li.somesel {
  display : block;
}

Test file:
Before
https://gist.github.com/deepak-jacob/90d5562d03b0d5e1c7f2b030386e270d
After
https://gist.github.com/deepak-jacob/6e814f85446749f136ad2675399a2fd4

Package version 2.6.0. 
Atom version 1.8.0

**Comment by SeanJM** [comment]
Fixed. I would highly recommend never using that selector.
