### ISSUE TITLE
Webkit Pseudo Classes being removed on cleaning

### ISSUE THREAD

**Issue by ArmandoValencia** [SeanJM/css-clean#25]
Hi, some elements in my css are being removed on cleaning. ¿This is an expected behavior? It affects this classes in particular, i haven't checked more, but if this issue is valid, i can help you check which other pseudo classes are being removed. 

  -webkit-column-count : 3;
  -moz-column-count    : 3;
  column-count         : 3;

Thank you.

**Comment by SeanJM** [comment]
I'm slowly refactoring the code for a new version, the issue here is that this property is just not listed in the properties list. It will take me a few weeks before I can fix this.

**Comment by xekri** [comment]
It's a serious problem. After a clean that deleted all the code that after "some invalid properties" in the class, I realized I have to stop use CSS clean plugin till you fix it…
A temporary solution is that put all "hack" properties in a separate file.
Come on and fix the annoying bug, and thanks for the plugin : ) .

**Comment by SeanJM** [comment]
I am almost there, have patience.

**Comment by SeanJM** [comment]
Done and fixed. Uploaded the refactored version 30 seconds ago.
