### ISSUE TITLE
Option for tabsize

### ISSUE THREAD

**Issue by xoxys** [SeanJM/css-clean#28]
Hi,
is it possible to make the tabsize optional? Otherwise users have to edit the specific file after every package update.

Thanks

**Comment by SeanJM** [comment]
Tab size is automatically detected. Just make sure your initial tab is what ever you want it to be.

**Comment by SeanJM** [comment]
I added automatic tab detection, try updating it and running it on a file with what ever your spaces are.

**Comment by xoxys** [comment]
Wow thanks for your very fast response. Working like a charm :)

**Comment by SeanJM** [comment]
You're welcome,  :)
