### ISSUE TITLE
Issue [Please include CSS in bug report]

### ISSUE THREAD

**Issue by CuriousPelican** [SeanJM/css-clean#9]
Hi, I would just like to say I have this issue where after I compile my sass to css and then try to tidy it up using css-clean it removes random letters, numbers and syntax and breaks my code.

Any fix for this?

**Comment by SeanJM** [comment]
If you post your CSS I will have a context for what broke it.

**Comment by SeanJM** [comment]
I am closing the issue as there is not enough evidence to solve it.
